[env]
TERM = "xterm-256color"

[font]
normal = { family = "CaskaydiaMono Nerd Font", style = "Regular" }
bold = { family = "CaskaydiaMono Nerd Font", style = "Bold" }
italic = { family = "CaskaydiaMono Nerd Font", style = "Italic" }
size = 12
offset = {x = 0, y = 0}

[terminal.shell]
program = "/bin/zsh"

[window]
opacity = 1
# opacity = 1
startup_mode = "Maximized"
# opacity = 1

[window.padding]
# x = 5

[selection]
save_to_clipboard = true

[colors]
draw_bold_text_with_bright_colors = false

# [general]
# import = ["~/.cache/wal/colors-alacritty.toml"]

[colors.primary]
background = '#1F1F1F'
foreground = '#D4D4D4'

[colors.cursor]
text = "#1F1F1F"
cursor = "#D4D4D4"

[colors.normal]
black = "#1F1F1F"
red = "#F44747"
green = "#6A9955"
yellow = "#DCDCAA"
blue = "#569CD6"
magenta = "#C586C0"
cyan = "#56B6C2"
white = "#D4D4D4"

[colors.bright]
black = "#808080"
